### ISSUE TITLE
Random Number Generation Uneven

### ISSUE THREAD

**Issue by iwiden3** [rohitsodhia/gamersplane.v1#1]
I have been playing a couple games on GamersPlane for several months. I have noticed that the random number generation has been uneven. During a recent fight, I recorded my parties rolls of d20s (100+) that happened in one thread. Here is the data I collected.

https://docs.google.com/spreadsheets/d/1pjQe2CuJC8RW0hKKwUptNNdikR45-5dXzDatTw07FE8/edit?usp=sharing

This seems to fail statistical tests for randomness. The low number of times a 10 has rolled seems to be statistically significant in itself.

I have looked at the code and it seems correct, but I think there might be an issue with the deployment. Perhaps the Random Number Generator is being seeded with low entropy somehow.

**Comment by rohitsodhia** [comment]
Thanks so much for this data! The server is old, and may have poor entropy. I'll look into increasing it if I can figure out how, otherwise, when I release the Angular update, I plan on launching a new server with all the updates.

On February 1, 2018 9:47:08 PM EST, iwiden3 <notifications@github.com> wrote:
>I have been playing a couple games on GamersPlane for several months. I
>have noticed that the random number generation has been uneven. During
>a recent fight, I recorded my parties rolls (100+) that happened in one
>thread. Here is the data I collected.
>
>https://docs.google.com/spreadsheets/d/1pjQe2CuJC8RW0hKKwUptNNdikR45-5dXzDatTw07FE8/edit?usp=sharing
>
>This seems to fail statistical tests for randomness. The low number of
>times a 10 has rolled seems to be statistically significant in itself.
>
>I have looked at the code and it seems correct, but I think there might
>be an issue with the deployment. Perhaps the Random Number Generator is
>being seeded with low entropy somehow. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rohitsodhia/gamersplane/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
